name: Publish Site
on:
    push:
        branches:
            - master
jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                submodules: true
            - name: Publish Site
              uses: chabad360/hugo-gh-pages@master
              with:
                githubToken: ${{ secrets.GITHUB_TOKEN }}
            - name: "parameters: set parameters"
              id: parameters
              run: |
                PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
                echo "::set-output name=pr_number::${PR_NUMBER}"                
            - name: "Failed Build Notify"
              if: failure()
              uses: rtCamp/action-slack-notify@v2.1.0
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_CHANNEL: app-delivery
                SLACK_TITLE: Failed Build - ${{ github.event.pull_request.title }}
                SLACK_COLOR: "danger"
                SLACK_USERNAME: 'GitHub Actions'
                SLACK_MESSAGE: |
                  This Github Actions workflow failed build.

                  Pull Request
                  ${{github.event.pull_request.url}}
                  https://github.com/${{github.repository}}/pull/${GITHUB_REF}